[package]
name = "proto"
version = "0.1.0"
authors = ["Jay Lee <busyjaylee@gmail.com>"]
edition = "2018"

[dependencies]
bytes = "1.0"
prost = "0.7"

[build-dependencies]
prost-build = { version = "0.6" }
